id: IFB787FFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T04:41:10+00:00'
last_modified: '2022-06-07T19:00:39.791910+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC305
  title: གསུང་འབུམ། སློབ་དཔོན་པདྨ་འབྱུང་གནས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    569E:
      image_group_id: I2PD17747
      title: ''
      total_pages: 782
      order: 1
      base_file: 569E.txt
    9B33:
      image_group_id: I2PD17748
      title: ''
      total_pages: 690
      order: 2
      base_file: 9B33.txt
    C865:
      image_group_id: I2PD17749
      title: ''
      total_pages: 726
      order: 3
      base_file: C865.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
